### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by evolutionjay** [nolimits4web/Framework7-Vue#1]
Framework7 + vue it would be amazing！！！
this is  vue + vuex + vue-router + vue-loader ?

**Comment by nolimits4web** [comment]
Just a Vue components with a custom routing I believe. Not sure about other

**Comment by evolutionjay** [comment]
Framework7 is the lack of "vuex" this state management library

**Comment by aliencyl7** [comment]
I really support this repo!!!! Awesome!!!! And there are two things confusing me in the f7 , and i really want to see the change in next milestone version
[ x ] the router that render a component without having a html page
[ x ] import component modularly

**Comment by nolimits4web** [comment]
@aliencyl7 these two problems are already solved in this repo

**Comment by akralj** [comment]
Excellent work so far. thanks a lot.
how much of the javascript of vanila framework7 are planning to use?
(<script src="framework7/framework7.js"></script>) 
Or will it be all gone once you are finished with this repo?
Routing was the most confusing part for me when using framework7. are you planning to use vue-router?

**Comment by nolimits4web** [comment]
@akralj no chances for Vue router, but this uses something similar. As for vanilla JS, it is not possible without it in many cases, but it will be much less of course

**Comment by yezongyang** [comment]
Framework7 is the lack of state manage

**Comment by cornelisse** [comment]
I agree with evolutionjay and yezongyang that vuex would be of great value to F7. But so far no complains, only applause !

**Comment by yongningfu** [comment]
It is a really amazing job. I realy like it.thanks @nolimits4web

**Comment by sy-ww-sun** [comment]
Great move towards the further strength improvement of Framework7, but an example or demo app is desperately desired~.

**Comment by leapon** [comment]
Nice and clean with Framework7 + Vue

I can't seem to find how to open a page using js code?. For example, I want to redirect to main page after login is successful.

**Comment by akralj** [comment]
Same here. Could you please explain shortly how the router should be used from javascript. 
How is it possible to have hash fragments added to the url?
Thanks a lot for your help.

**Comment by leapon** [comment]
@akralj a solution is provided by @damir in #13

**Comment by akralj** [comment]
thanks @leapon.
what about adding hash fragments to the url?

**Comment by scriptPilot** [comment]
I really appreciate your good work, Vladimir! I try to contribute with a framework, based on Framework7, but with more features which are required mostly for every project ... for me ... to build web apps. So, everybody, feel free to take a look ... work is in progress, but you can comment if you want :-)

https://github.com/scriptPilot/framework7-vue-firebase

**Comment by cornelisse** [comment]
Very appreciate F7-vue-Firebase contribution by scriptPilot
