### ISSUE TITLE
Vue lifecycle and Framework7 router

### ISSUE THREAD

**Issue by xdadda** [nolimits4web/Framework7-Vue#100]
Hi guys
I'm having some issues handling vue's lifecycle hooks [LINK](http://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram)

Created() and mounted() are fired correctly when I access a page with f7 router.
But when i move to a new page ($router.load({url: '/test/'})) the destroyed() hook is not fired!

any advise? thanks

**Comment by xdadda** [comment]
just for the record; I figured it out
.load just caches pages
.reloadPage will destroy pages and fire all hooks

**Comment by HoldSkill** [comment]
hi, how to use reloadPage?
