### ISSUE TITLE
f7-vue can't run on Android v5.1.1 build in browser

### ISSUE THREAD

**Issue by BelinChung** [nolimits4web/Framework7-Vue#108]
### Mobile Name 
OPPP R9 Plusm A

### Android Version 
5.1.1

### Browser UA 
Mozilla/5.0 (Linux; U; Android 5.1.1; zh-cn; OPPO R9 Plusm A Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/38.0.0.0 Mobile Safari/537.36 OppoBrowser/4.2.8

### Steps to reproduce
Just simple run [nolimits4web/Framework7-Vue-Webpack-Template](https://github.com/nolimits4web/Framework7-Vue-Webpack-Template), issue can be easy reproduced.

### What is actually happening
![image](https://cloud.githubusercontent.com/assets/4954264/23832475/b0ba6afc-076f-11e7-8252-f9ebf9aa617c.png)

App's router become unavailable. Sorry for my debugger, there is not more clear message for your.

**Comment by konstantin-popov** [comment]
I think the problem is described in #129, check it out.

**Comment by BelinChung** [comment]
@konstantin-popov Yes, you are right! Thanks!
