### ISSUE TITLE
Nested Routes at Home ("/") Page 

### ISSUE THREAD

**Issue by alionfalcon** [nolimits4web/Framework7-Vue#110]
I'd like to report an issue I just encountered.

The default nested route (top stories) does not load until I click to its tab link. Both tabs work when I click on to link.

Please let me know if you need more information.

Thanks,

Here is a snipped: 

```
//// App.vue ////
<template>
  <!-- App -->
  <div id="app">
    <!-- Statusbar -->
    <f7-statusbar></f7-statusbar>

    <!-- Main Views -->
    <f7-views>
      <f7-view main id="main-view" navbar-through :dynamic-navbar="true">
        <f7-pages>
          <!-- Tabs Page with no-page-content-->
          <f7-page>
            <f7-block inner>
              
                <f7-link route-tab-link="#top-stories-tab" href="/" active>
                  Top Stories
                </f7-link>
                <f7-link route-tab-link="#latest-stories-tab" :href="'/latest/'">
                  Latest Stories
                </f7-link> 
          
            </f7-block>
            <f7-tabs>
              <f7-tab route-tab-id="top-stories-tab" />
              <f7-tab route-tab-id="latest-stories-tab" />     
            </f7-tabs>
          </f7-page>
        </f7-pages>
      </f7-view>
    </f7-views>
```

```
//// routes.js ////
  {
      path: '/',
      //component: ???,
      tabs: [
        {
          path: '/',
          tabId: 'top-stories-tab',
          component: Stories
        },
        {
          path: '/latest/',
          tabId: 'latest-stories-tab',
          component: Stories
        }
      ]
  },...
```

**Comment by bencompton** [comment]
I was able get it working with v0.8.5 by making a couple of changes to your example code. The main parts I changed from your code are :

1. Adding a URL attribute to the view so it will load a route within the view by default

2. Pulling out the tabs into a separate page, making that page the root route component, and restructuring the tabs a bit (I was assuming you wanted a tab bar).

```javascript
//// routes.js ////
  {
      path: '/',
      component: Tabs,
      tabs: [
        {
          path: '/',
          tabId: 'top-stories-tab',
          component: Stories
        },
        {
          path: '/latest/',
          tabId: 'latest-stories-tab',
          component: Stories
        }
      ]
  },...

/// app.vue ///
<template>
  <!-- App -->
  <span>
    <!-- Statusbar -->
    <f7-statusbar></f7-statusbar>

    <f7-views>
      <f7-view main id="main-view" navbar-through :dynamic-navbar="true" url="/">
        <f7-pages></f7-pages>
      </f7-view>
    </f7-views>
  </span>
</template>
<script>
export default {}
</script>

/// tabs.vue ///
<template>
    <f7-page tabbar-fixed>
            <f7-block tabs>
                <f7-tab route-tab-id="top-stories-tab" />
                <f7-tab route-tab-id="latest-stories-tab" />                 
            </f7-block>
            <f7-toolbar tabbar labels>
                <f7-link route-tab-link="#top-stories-tab" href="/" text="Top Stories" active />
                <f7-link route-tab-link="#latest-stories-tab" href="/latest/" text="Latest Stories" />
            </f7-toolbar>  
    </f7-page>
</template>
<script>
    export default {}
</script>
```

**Comment by alionfalcon** [comment]
This really helped thank you! 
(I wanted a top navbar as tabs but I think I can figure it out)

**Comment by imrealashu** [comment]
@bencompton thanks man, you've saved my day. really appreciated.

**Comment by bencompton** [comment]
@imrealashu - glad I could be of service.

**Comment by sudoak** [comment]
@bencompton I used your code, it doesn't load the url="/"

main.vue
<template>
  
  <div id="app">
    
    <f7-statusbar></f7-statusbar>

    <f7-views>
      <f7-view main url="/" id="main-view" navbar-through :dynamic-navbar="true">
        <f7-pages></f7-pages>
      </f7-view>
    </f7-views>
  </div>
</template>
<script>
export default {}
</script>

tabs.vue

<template>
            <f7-page tabbar-fixed>

    <f7-block tabs>
      <f7-tab id="tab1" />
      <f7-tab id="tab2" />
      <f7-tab id="tab3" />
    </f7-block>

    <f7-toolbar tabbar labels>
      <f7-link href="/" route-tab-link="#tab1" text="Tab 1" active></f7-link>
      <f7-link href="/tab-2/" route-tab-link="#tab2" text="Tab 2"></f7-link>
      <f7-link href="/tab-3/" route-tab-link="#tab3" text="Tab 3"></f7-link>
    </f7-toolbar>

  </f7-page>
</template>

<script>
export default {
  
}
</script>

routes.js

 path: '/',
    component: require('./assets/vue/pages/tabs.vue'),
    tabs: [
      {
        path: '/',
        tabId: 'tab1',
        component: require('./assets/vue/pages/tab1.vue')
      },
      {
        path: '/tab-2/',
        tabId: 'tab2',
        component: require('./assets/vue/pages/tab2.vue')
      },
      {
        path: '/tab-3/',
        tabId: 'tab3',
        component: require('./assets/vue/pages/tab3.vue')
      }
    ]
  }
