### ISSUE TITLE
pushState not working for the vue version?

### ISSUE THREAD

**Issue by etiennea** [nolimits4web/Framework7-Vue#111]
Has anyone managed to get this working? Thanks!

**Comment by nolimits4web** [comment]
Yes, it should work

**Comment by etiennea** [comment]
Ok I had to make one of my views "main" for it to work

**Comment by rvanzon** [comment]
@etiennea did you make it work with a tabbar/toolbar? Adding `view-main` enables pushState for that screen only, but switching views by tapping on the tabs. I tried to add `view-main` to the underlying div (#app), but that didn't work. Any ideas?

**Comment by ijry** [comment]
i have same problem
