### ISSUE TITLE
pushState shows double slash

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7-Vue#118]
After enabling pushState in framework7, each routing is shown in the URL with double slash - for example with first sub page in the kitchen sink:

`http://localhost:8080/#!//content-block/`

**Comment by nolimits4web** [comment]
Look at http://framework7.io/docs/init-app.html and `pushStateSeparator` parameter, set whatever you need there

**Comment by scriptPilot** [comment]
@nolimits4web - As I see it, the current default setup is as follows:

- In kitchen sink, all urls are "/.../"
- Separator is "#!/"

So, the output is "#!//.../" after click on any link.

For me, that behavior is not correct. Either the link should not start with a slash or the default separator should not end with a slash.

What do you think?

**Comment by nolimits4web** [comment]
Don't rely on Kitchen Sink, it is just for example. So just set separator to `#!` to remove double slashes in your app or don't start links with slash, use whatever is fit best for you

**Comment by scriptPilot** [comment]
@nolimits4web - OK, is there any argument to link with "/page/" or is "page" good to use?

**Comment by ZanderBrown** [comment]
Butting in slightly:

Having a empty seperator and opening an absolute link (starts with `/`) does result in double `/` (http://example.com//test). Of course you can't use a relative link because then the links will be broken when resuming from a bookmark
