### ISSUE TITLE
Vue warning - no keys in lists

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7-Vue#121]
Should be similar to #58 

![bildschirmfoto 2017-03-22 um 16 09 26](https://cloud.githubusercontent.com/assets/19615586/24204852/02115274-0f1a-11e7-9c4f-89e1d91471c7.png)

**Comment by nolimits4web** [comment]
Because demo list - with demo data doesn't have keys. It is not an issue of plugin
