### ISSUE TITLE
how to use destroyed in this project?

### ISSUE THREAD

**Issue by HoldSkill** [nolimits4web/Framework7-Vue#124]
hi, when i leave this page , i want to 'unuse' css in destroyed, but destroyded not working ,why?thank you~

**Comment by nolimits4web** [comment]
destroyed in Vue works when component is destroyed/detached. When you load new page the previous one is still in DOM. Pages are getting destroyed when you go back in history or use "reload" method to load the page

**Comment by HoldSkill** [comment]
thank you very much~
