### ISSUE TITLE
ie 11 does not work, because it does not support Object.assign

### ISSUE THREAD

**Issue by akralj** [nolimits4web/Framework7-Vue#129]
Hi,
Object.assign is used there in 4 places[ (see this link)](https://github.com/nolimits4web/Framework7-Vue/search?utf8=✓&q=Object.assign&type=))

Using this polyfill fixed it for me:
https://github.com/rubennorte/es6-object-assign
It would be great to add this to framework7-vue to make ie 11 happy.

**Comment by bencompton** [comment]
Hey, nice job getting it working in IE. I think adding a polyfill in your own project is a perfectly reasonable solution. I can't imagine that a lot of people are using F7 with IE (but who knows, I may be surprised), so I'm not sure it is worth adding the polyfill as a dependency to F7 Vue. It is nice how F7 Vue is so compact with no dependencies right now.

**Comment by konstantin-popov** [comment]
Actually, this problem also applies to Android at least up to and including 5.1 (see http://kangax.github.io/compat-table/es6/).

**Comment by bencompton** [comment]
@konstantin-popov, good point. I suppose the appropriate [Babel transform](https://babeljs.io/docs/plugins/transform-object-assign/) could be added then.

**Comment by konstantin-popov** [comment]
@bencompton, looks like a good solution too.
I understand you don't want to add extra dependencies and it could easily be done on app level, but may be this should be added into the docs?
AFAIK Framework7 itself supports Android 4.4+, Vue.js supports Android Browser 4.2+, so if Framework7-vue has other environment requirements it should be mentioned somewhere, possibly with a brief description of possible workarounds.

**Comment by scriptPilot** [comment]
Instead of creating a dependency, is there any point against the proposition just to add the code from the polyfill directly to F7Vue ?

**Comment by mix3d** [comment]
Why was this closed? 

Is there a preferred way to run the polyfill on the f7-vue module through webpack/babel?
