### ISSUE TITLE
how to delete these cached page?

### ISSUE THREAD

**Issue by HoldSkill** [nolimits4web/Framework7-Vue#133]
![image](https://cloud.githubusercontent.com/assets/25190239/24957721/39d38e10-1fbf-11e7-9c63-11586fe2a522.png)

hello~
1、when i try to use this url http://127.0.0.1:8081/#/lecture/room/?id=1 to go to the room.vue page, the app will go to the index page ? why? 
2、how to hide or delete these cached pages?
3、thank you very much~

**Comment by JonSmart** [comment]
#160

**Comment by araimbekoff** [comment]
Try to pass the parameters without the "?" For this purpose in a router to register 
/your_page/:your_param
Access to the parameter in the code: this.$router.param.your_param

**Comment by nolimits4web** [comment]
Set `:domCache="false"` on View

**Comment by JonSmart** [comment]
I am experiencing issues with `:domCache="false"` if the user navigates beyond 2 pages deep, i.e. Open a page, then another page, then another page when going back the first time everything is ok, but when returning again the page renders but is not connected to the Vue component so no clicks or anything work.

**Comment by teddy-dubal** [comment]
@JonSmart i've got the same problem , do you find a workaround ?

**Comment by JonSmart** [comment]
Sadly I had to do a work around that was not ideal.  I did something along the lines of reload the page when detecting that back navigation happened.  It was messy and caused some other issues, I have reduced the 3 deep scenario where possible.
