### ISSUE TITLE
V-Model on "opened" properties

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7-Vue#135]
Hi Vladimir,

I set `:opened="leftPanel"` on a panel and `leftPanel: false` in the data object.

Then I add a link with `@click="leftPanel=true"` - everything works fine, clicking the link opens the panel.

Now, when I close the panel - leftPanel is still true.

The issue - Clicking again on the link does not open the panel again.

My idea - using v-model - But that doesn't work so far.

So, I would suggest to add the possibility to use v-model for all **opened** properties.

What do you think?

Dennis

**Comment by nolimits4web** [comment]
`v-model` is designed ONLY to be used with form inputs. So no chances here. If you use state to open panel (using `leftPanel`) in your example. Then close it using same method by assigning `leftPanel = false`

**Comment by nolimits4web** [comment]
Or add `@panel:closed="leftPanel = false"` event callback
