### ISSUE TITLE
how to set smart select value

### ISSUE THREAD

**Issue by pakyo-pan** [nolimits4web/Framework7-Vue#139]
![image](https://cloud.githubusercontent.com/assets/13342613/25112763/ee8bf0da-2425-11e7-8965-0cc08abfebeb.png)
f7 vue, how to set smart select value ?
thank you ~

**Comment by ijry** [comment]
+1 and how to get smart select's value with vue?

**Comment by ijry** [comment]
@nolimits4web thks

**Comment by 7aduta** [comment]
any help on that matter ?

**Comment by skycult** [comment]
@nolimits4web can I solve this problem? Thank you

**Comment by mgesmundo** [comment]
Hello @nolimits4web do you have some workaround for this?
Thanks
Best regards

**Comment by skycult** [comment]
Any news about this issue?
Thks

**Comment by nolimits4web** [comment]
How to set or get? If you need to set it just set "selected" attribute on required `<option>`. If your options are got added later (like via Ajax request) then you can also set it manually as value of `after` prop

**Comment by skycult** [comment]
Thank you Vladimir, but the smart select should emit an "input" event when I change the selection on the smart-select. In a project using Vuex, if I change a selection on the smart select I need to update the store, but the "input" (and "change") event is not fired. In the "vue vision" when a value is updated, the "input" event should be fired.
Thank you.
