### ISSUE TITLE
Icons are to big in general

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7-Vue#14]
Minor issue - icons are displayed to big within text blocks.

```
<f7-block inner inset>
  <f7-icon f7="info" /> All the following examples and the side panels are in English only.
</f7-block>
```

![screenshot 3](https://cloud.githubusercontent.com/assets/19615586/21143133/c2773ace-c145-11e6-94fe-592b96189cf4.png)

**Comment by scriptPilot** [comment]
The same for material icons - I think it's a general issue, are the icons with fixed size?

```
<f7-block style="text-align: center">
  <small>
    <f7-icon material="build"></f7-icon>&nbsp;Version 0.3.3
  </small>
</f7-block>```

![screenshot 4](https://cloud.githubusercontent.com/assets/19615586/21149838/23191db8-c15d-11e6-9bf6-07aacde239e3.png)

**Comment by pshendry** [comment]
This library has no CSS, so the icon size is whatever the default is (or whatever you've styled it to).

Looking at [the docs for Framework7](https://framework7.io/docs/icons.html), the default seems to be 25px. Just use `font-size` to resize the element (see example in the docs).

**Comment by scriptPilot** [comment]
Created incident in [Framework7 repo](https://github.com/nolimits4web/Framework7/issues/1251)
