### ISSUE TITLE
f7-list-item wrongly render "data-view" attribute

### ISSUE THREAD

**Issue by kevinqqnj** [nolimits4web/Framework7-Vue#142]
According to doc.: [http://framework7.io/vue/list-item.html](http://framework7.io/vue/list-item.html)

Links Items:
```
<f7-list>
  <f7-list-item link="/about/" title="About"></f7-list-item>
</f7-list>
```

Renders to:

```
<div class="list-block">
  <ul>
    <li>
      <a href="/about/" class="item-link">
        <div class="item-content">
          <div class="item-inner">
            <div class="item-title">About</div>
          </div>
        </div>
      </a>
    </li>
  </ul>
</div>
```
But if you add **"data-view"** attribute:
```
<f7-list-item link="/about/" data-view="#main-view" title="About"></f7-list-item>
```

it's wrongly be rendered to ```<li>``` element, which should be in ```<a>``` element. It will cause Split-View layout not working due to not refer to correct view.
```
<div class="list-block">
  <ul>
    <li class="" data-view="#main-view">
      <a href="/about" class="item-link">
        <div class="item-content">
          <div class="item-inner">
            <div class="item-title">About</div>
          </div>
        </div>
      </a>
    </li>
  </ul>
</div>
```

So: suggest to update f7-list-item component, to render different attributes to relative elements!

Thanks//Kevin

**Comment by nolimits4web** [comment]
It is expected behavior and this is how Vue renders attributes. Use `link-view` prop instead
