### ISSUE TITLE
this.$f7 in undefined without timeout

### ISSUE THREAD

**Issue by lcaprini** [nolimits4web/Framework7-Vue#146]
Hi, I'm using `this.$f7.showPreloader()` function of F7 framework in `mounted()` VueJS's life cycle event, but I've the following error:
`vue.common.js:1449 TypeError: Cannot read property 'showPreloader' of undefined`.

If I call it inside a `setTimeout` it works correctly:
```
setTimeout(()=>{
  this.$f7.showPreloader();
}, 2000);
``` 

There is a way to know when `$f7` is available in Vue component?
Thank you

**Comment by scriptPilot** [comment]
You can use the method `onF7Init`, which will called after F7 init.

**Comment by scriptPilot** [comment]
@lcaprini - You can listen as well to the f7Ready event:

````
beforeCreate: function () {
    this.$on('f7Ready', function () {
      console.log('Framework7 is ready ...', this.$f7)
    }.bind(this))
  }
````

**Comment by nolimits4web** [comment]
Yes, use `onF7Init` method for initial components:
```js
methods: {
  onF7Init: function (f7) {
    //available here
  }
}

**Comment by lcaprini** [comment]
Perfect! I have not seen `onF7Init` event in documentation;
Thank you for your support.
