### ISSUE TITLE
 f7-input causes an error '"style" is a reserved attribute...'

### ISSUE THREAD

**Issue by araimbekoff** [nolimits4web/Framework7-Vue#148]
I updated from 0.8.5 to 0.9.0 (framework7 v-1.5.4 -> 1.6.0). Now an error occurs:
"style" is a reserved attribute and cannot be used as component prop.

I use the material theme.

        <f7-list-item>
          <f7-label floating>Your UIN</f7-label>
          <f7-input type="text" placeholder="" v-model="agent_uin" @keyup="agent_search"></f7-input>
          <f7-label>{{((agent_uin + '').length == 12) ? 'Нажмите ввод/enter ' : ''}}</f7-label>
        </f7-list-item>

This Warning is everywhere where I use f7-input ((

**Comment by centrual** [comment]
I saw this error in `F7Switch` and `F7Input`

**Comment by JonSmart** [comment]
I have temporarily removed it by removing `style: String` from `props` and 'attrs` in the form-input.vue src file. Haven't had chance to fork and make a pull request yet.

**Comment by araimbekoff** [comment]
I tried. 
Problem still exists ((

**Comment by KirinHuang** [comment]
Problem still exists +1

**Comment by PhilippeAssis** [comment]
Problem still exists +1

**Comment by auzadventure** [comment]
Problem still exists +1

**Comment by KirinHuang** [comment]
@PhilippeAssis @auzadventure you can find solution #157 and the commit #156

**Comment by Windancer** [comment]
Problem still exists +1

**Comment by dunice-boldirev** [comment]
Problem still exists +1

**Comment by araimbekoff** [comment]
https://gist.github.com/rvanzon/a83b579d7c077
5150ca51c6a3b0a0389
Try it

**Comment by araimbekoff** [comment]
https://gist.github.com/rvanzon/a83b579d7c0775150ca51c6a3b0a0389

**Comment by varunajmera0** [comment]
Go to package.json
update ur framework7-vue dependency
"dependencies": {
    "framework7": "^1.5.2",
    "framework7-vue": "^0.9.2",
    "vue": "^2.1.0"
  }
It will work fine.

**Comment by monmon29** [comment]
@varunajmera0 , that works to me. Update the package.json then perform "npm install"

**Comment by Jaspur** [comment]
Issue still occurs. I'm on the last versions of Frameowkr7

**Comment by monmon29** [comment]
@Jaspur , try ko downgrade.
