### ISSUE TITLE
how to set a page as init page?

### ISSUE THREAD

**Issue by ijry** [nolimits4web/Framework7-Vue#158]

**Comment by nolimits4web** [comment]
https://github.com/nolimits4web/Framework7-Vue/blob/master/kitchen-sink/index.html#L38-L41

**Comment by ijry** [comment]
this does not work?

**Comment by ijry** [comment]
![default](https://cloud.githubusercontent.com/assets/3102798/26054698/13a122c0-39a0-11e7-8b9b-9e0f2db89e96.PNG)
