### ISSUE TITLE
how to disable page cache ?

### ISSUE THREAD

**Issue by ijry** [nolimits4web/Framework7-Vue#160]
this may bring bad experience on webview ,so can i use someting to disable page cache?
![default](https://cloud.githubusercontent.com/assets/3102798/25800555/6c83e7da-341c-11e7-9f62-568d65e16caa.PNG)

**Comment by JonSmart** [comment]
Adding the attribute domCache to the `<f7-view ` with no value stops caching, this is probably not the best solution, but I have just had the same issue.

**Comment by JonSmart** [comment]
I think this can be disabled correctly in 0.9.0 by adding `:domCache="false"`

**Comment by AysadKozanoglu** [comment]
The simplest way is to define a variable _timestamp_ and set it with _Date.now()_ and give it to route path parameter with _?timestamp_ on every route path ending. 

So in this case framework7 must load every html file on every browser reload again.

after your development and design is finished you can comment it out. This scenario you can use for every framework you use. it is not framework7 specific. 

for examle:
<pre>
var timestamp   = Date.now();

routes = [
  {
    path: '/',
    url: './index.html?'+timestamp,
  },
  {
    path: '/about/',
    url: './pages/about.html?'+timestamp,
  },
  {
    path: '/form/',
    url: './pages/form.html?'+timestamp,
  },
  {
    path: '/page-loader-template7/:user/:userId/:posts/:postId/?'+timestamp,
    templateUrl: './pages/page-loader-template7.html?'+timestamp,
  },
  {
    path: '/page-loader-component/:user/:userId/:posts/:postId/?'+timestamp,
    componentUrl: './pages/page-loader-component.html?'+timestamp
  }]
</pre>
