### ISSUE TITLE
Update progress bar

### ISSUE THREAD

**Issue by lcaprini** [nolimits4web/Framework7-Vue#168]
Hi, I'm using `f7-progressbar` but the prop `:progress='count'` doesn't update when `count` changes.
How can I update the progress bar dinamically?

Thank you

**Comment by rvanzon** [comment]
I just checked and it works. Be sure to define count in `data`. So something like:

```javascript
data () {
    return {
      count: 0
    }
  },
```

Then just use it in your code like `this.count += 10`

**Comment by nolimits4web** [comment]
@rvanzon 👍
