### ISSUE TITLE
help!! not with the tabbar or url, how to access the homepage under views and pages tag?

### ISSUE THREAD

**Issue by liygogo19** [nolimits4web/Framework7-Vue#169]

**Comment by rvanzon** [comment]
please add some more info in the description field of the issue.

**Comment by nolimits4web** [comment]
Closing as there is no information

**Comment by liygogo19** [comment]
sorry, i forget to check this problem, i mean how to access the home page, because i don't want to use the :url this way, but this.$f7.getCurrentView().router.back({pageName:'home-page', force: true} doesn't work, is here any way else to access the page in the app.vue(f7-page part)?
