### ISSUE TITLE
f7-input resizable textarea doesn't work.

### ISSUE THREAD

**Issue by rvanzon** [nolimits4web/Framework7-Vue#171]
When setting a f7-input to resizable doesn't result in a resizing textarea. I checked the HTML: the Vue version:

`<f7-input type="textarea" resizable></f7-input>`

is the same as the plain html versions:

`<div class="item-input"><textarea class="resizable"></textarea></div>`

The difference is that the parent of the textarea (item-input) doesn't get `style="width: ???px"` in the Vue-version when the text changes.

It seems the F7 doesn't watch the height of the textarea.

**Comment by nolimits4web** [comment]
1) Make sure you are using 0.9.0 + version of Vue plugin
2) If you change the value of textarea programmatically, then you need to trigger 'change' event on it after you change its value

**Comment by rvanzon** [comment]
unfortunately I am using 0.9.0 (cloned repo) and I am not changing it programmatically. I checked the source and I saw there are no events handled in Vue, so I assume it's done in the framework. I could add this in my Vue-component.

I really think the framework doesn't watch the textarea for some reason. Maybe because the event is not bound? Or it's not able to set the style of the parent.

**Comment by rvanzon** [comment]
I made a fiddle: https://jsfiddle.net/rvanzon/3oq8Lk1u/

**Comment by nolimits4web** [comment]
Ok, it happens because you don't use full correct structure. You need to have View -> Page structure, because F7 init all the stuff in pageInit callback/event. In your case you may use `f7.resizableTextarea('textarea')` to init and start watching it

**Comment by rvanzon** [comment]
@nolimits4web ah yes, adding a f7-view and f-page makes it work: https://jsfiddle.net/rvanzon/3oq8Lk1u/2/ 
thanks! Also for your fast response. Just great!

Though, I am using the f7-input on a popup, and it seems off to add a f7-view there. Or is this intentional?

**Comment by rvanzon** [comment]
@nolimits4web I keep having problems using resizable textarea's in popup? Sometimes it seems to work (I think because of `this.$f7.resizableTextarea('textarea')`), but mostly it doesn't. Any ideas?
