### ISSUE TITLE
how to set a page as init page?

### ISSUE THREAD

**Issue by ijry** [nolimits4web/Framework7-Vue#172]
https://github.com/nolimits4web/Framework7-Vue/blob/master/kitchen-sink/index.html#L38-L41

i  do as this , but nothing happened really?

**Comment by ijry** [comment]
@nolimits4web

**Comment by nolimits4web** [comment]
Make sure you are using latest F7-Vue plugin. And as you may see it works correct in Kitchen Sink

**Comment by ijry** [comment]
i find the problem, the pages  inside need to be empty,thenit can  worked.
