### ISSUE TITLE
swipeout delete two list-items if also update the data

### ISSUE THREAD

**Issue by red010182** [nolimits4web/Framework7-Vue#175]
Please check the [fiddle](https://jsfiddle.net/a353jcds/13/)

Problem: swipeout delete a list-item will eventually delete 2 list-items if you also update the data (`users` in following example).

In the following example, if you swipeout delete one of 1st~3rd user, it will delete 2 users.

If I do nothing in `deleteUser` function, everything works fine at view layer, but I need my data be updated as well! What is the correct way to swipeout delete item and reflect it to data? 

```

<f7-list>
    <f7-list- v-for="(user,i) in users" :title="user.name" swipeout @swipeout:deleted="deleteUser(i)">
       <f7-swipeout-actions>
            <f7-swipeout-button delete>Delete</f7-swipeout-button>
       </f7-swipeout-actions>
    </f7-list-item>
</f7-list>



new Vue({
  el: '#app',

  data: {
    users: [{name:"Andy"},{name:"Bill"},{name:"Cindy"},{name:"David"}]
  },
  
  methods: {
    deleteUser(i) {
      this.users.splice(i,1);
    }
  },
  
  framework7: {
    root: '#app',
    routes: [],
  }
})
```

**Comment by nolimits4web** [comment]
You can set `swipeoutRemoveWithTimeout: true` f7 app parameter. In this case Vue will remove element from Dom instead of F7.
