### ISSUE TITLE
How to use Vue-Router instead of default router?

### ISSUE THREAD

**Issue by red010182** [nolimits4web/Framework7-Vue#177]
Is it possible to use Vue-Router instead of Framework7-Vue's default router? How to setup? How should I make tab routes work if I use Vue-Router? 

Because Framework7-Vue's default router is so limited and sometimes probelmatic, for example:

* Lack of the ability passing javascript object as props
* Sometimes got `this.$route=undefined` or `this.$router=undefined` in vue object even if it's routed correctly.
* Routes depends on view hierarchy, the same link may be routed differently in different pages. For example: 
Page1 -> route to `/user/1` -> Works
Page1 -> Page2 -> route to `/user/1` -> Fail (`userVue.$route=undefined`)

* You need to use `$f7.views.main.router` or `$f7.mainView.router` instead of `$router` before  framework7's router actually route some page. In this case, you have to use 2 routers...
* It makes tab routes so complicated. I think tabs should not be controlled by router! It should as easy as  make the page show or hide.
* `$route.params` should delegate to props, but it doesn't.

**Comment by nolimits4web** [comment]
Vue-Router is not supported. As for tabs you may Switch them without Router: http://framework7.io/vue/tabs.html#switch-tabs
