### ISSUE TITLE
Image/html in f7-message

### ISSUE THREAD

**Issue by etiennea** [nolimits4web/Framework7-Vue#184]
In f7 this is how you send a pic in messages 

```
<div class="message message-sent">
        <div class="message-text"><img src="http://lorempixel.com/300/300/"></div>
        <div class="message-label">Delivered 2 days ago</div>
      </div>
```

but in f7-vue the <f7-message :text="does not take html!"

maybe there should be a :html=?

**Comment by bencompton** [comment]
The Message component has the default slot under the div with `message-text`: https://github.com/nolimits4web/Framework7-Vue/blob/master/src/components/message.vue.

I think something like this should accomplish what you're trying to do:

```javascript
<f7-message>
  <img src="..." />
</f7-message>
```

**Comment by etiennea** [comment]
A yes perfect! Maybe that should just be in the docs!
