### ISSUE TITLE
back's page need data update?

### ISSUE THREAD

**Issue by ijry** [nolimits4web/Framework7-Vue#186]
when i back to pre page,  such as login.vue back to usercenter.vue. the pre page need tobe updated, but f7's route  read the dom's cache on-the-left, this confused me ?

**Comment by ijry** [comment]
please ， this  is  urgent !

**Comment by ijry** [comment]
this.$router.back({ignoreCache:true});   this ignoreCache:true never work which maker me wonder.

**Comment by araimbekoff** [comment]
try it this.$router.back({iurl:'page-name'});

**Comment by ijry** [comment]
@araimbekoff  never worked!

**Comment by araimbekoff** [comment]
sorry!
`this.$router.back({url:'page-name', force:true});`
[Watch here](http://framework7.io/docs/router-api.html)

or
`this.$router.reloadPreviousPage(url)`

**Comment by ijry** [comment]
never worked all of this, so i compused!

**Comment by ijry** [comment]
the back's options seems  never got received

**Comment by ijry** [comment]
![qq 20170616122115](https://user-images.githubusercontent.com/3102798/27211797-653c59b8-528e-11e7-9f21-099ab23bbca4.png)

the back method can only  got those prams.

**Comment by ijry** [comment]
whatever you pass url force or something else ,you will not see it in back method's options.

**Comment by ijry** [comment]
@araimbekoff

**Comment by ijry** [comment]
i donnot what happened with my route!!

**Comment by nolimits4web** [comment]
Duplicate of #201
