### ISSUE TITLE
how to listen android's backbutton event?

### ISSUE THREAD

**Issue by ijry** [nolimits4web/Framework7-Vue#194]
how to listen android's backbutton event and handle with this.$router.back();

**Comment by ijry** [comment]
where can  i put code like below?
`
// 监听安卓返回按键事件
var onBackKeyDown = function() {
    alert('asdaw');
    下面的if判断页面是否是首页如果是才执行，否则执行else的返回上一页
    if (myApp.getCurrentView().url == '/home/') {
        alert('再点击一次退出!');
        document.removeEventListener("backbutton", onBackKeyDown, false); // 注销返回键
        document.addEventListener("backbutton", function(){navigator.app.exitApp();}, false);// 通过监听返回键绑定退出事件
        // 3秒后重新注册
        var interval_id = window.setTimeout(function() {
            window.clearTimeout(interval_id);
            document.removeEventListener("backbutton", function(){navigator.app.exitApp();}, false); // 注销返退出事件
            document.addEventListener("backbutton", onBackKeyDown, false); // 返回键
        }, 3000);
    } else {
        myApp.getCurrentView().router.back();  // 后退
    }
}
// 安卓返回按钮监听
if (device.platform == "Android") {
    document.addEventListener("backbutton", onBackKeyDown, false);
}
`
@nolimits4web @macdonst

**Comment by 01abhishekjain** [comment]
`document.addEventListener('backbutton', handleBackButton);`

you can put it in the main.js file
