### ISSUE TITLE
cannot use twice of $route?

### ISSUE THREAD

**Issue by ijry** [nolimits4web/Framework7-Vue#199]
![qq 20170622211903](https://user-images.githubusercontent.com/3102798/27436044-843b4688-5790-11e7-8f4e-dca002325294.png)

**Comment by ijry** [comment]
this.$router.refreshPreviousPage();  this worked, but this.$router.back(); not work?

**Comment by edgardleal** [comment]
See the issue #202 and tell me if it solve this problem.

**Comment by nolimits4web** [comment]
There is no sense in such usage, call back method with passed url and force:true to go back to reloaded page
