### ISSUE TITLE
Why the $router is unavailable

### ISSUE THREAD

**Issue by araimbekoff** [nolimits4web/Framework7-Vue#204]
Where is the router initialized? I try to take it through this.$router in onF7Init,  but he undefined (
Why?

**Comment by araimbekoff** [comment]
The problem is as follows:
Immediately after loading the page, $ router is not initialized. If you first go to any <f7-link href = 'another-link'> </ f7-link> link, then $ router becomes available.
Is this a bug or a feature?

HELP!

**Comment by clockworked247** [comment]
@araimbekoff I got hung up on this for a while too, but after some digging through the docs, I found the answer in the fine print: 
https://framework7.io/vue/navigation-router.html#router-api

`Please note, that $route and $router component properties are only available inside of custom page components (and their child components) that you load according to routes. In parent components (like in View, or where you init your Vue app instance) they are not accessible as your app may have few routers (Views) at a time. So in this case use access to initialized View Instance, e.g. $f7.views.main.router or $f7.mainView.router`

$f7.views.main.router was undefined ($f7.views was an array of views, so you can't access by the . selector "main"), but using $f7.mainView.router worked great for me from within the main page.

Hope that helps.

**Comment by araimbekoff** [comment]
@clockworked247 Thank you! You helped me!
