### ISSUE TITLE
infinite-scroll-preloader property toggel does not work

### ISSUE THREAD

**Issue by ralstan-vaz** [nolimits4web/Framework7-Vue#207]
Tried to bind the infinite-scroll-preloader property to a v-model
And tried the below
```
      this.loader = true;
      setInterval(() => {
        if (this.loader) {
          this.loader = false;
        } else {
          this.loader = true;
        }
      }, 2000);
```
The loader appears 1st
Then when it enters the setInterval the loader stops appearing on UI

#### Suggestion
Saw the below code in /src/components/page.vue

I think this may be the issue
```
      if ((self.infiniteScroll || self.infiniteScroll === '') && self.infiniteScrollPreloader) {
        infiniteEl = c('div', {class: {'infinite-scroll-preloader': true}} ,[
          c('div', {class: {'preloader': true}})
        ]);
      }
```

**Comment by nolimits4web** [comment]
`v-model` is for inputs only in Vue! Use `v-bind` to bind properties and attributes
