### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by pshendry** [nolimits4web/Framework7-Vue#21]
In particular:

* This library is installable using `npm`, but the docs only describe manually copying the JS file in `dist`;
* There aren't any "getting started" instructions
  * Is there an example/starter project we could link to for someone to use as a starting point?
  * Just a blurb explaining to go to `kitchen-sink` for usage examples and to `src/components` to see the props of each component would be helpful
* The way routing works could use explaining

**Comment by nolimits4web** [comment]
I'm currently working on the documentation website, should be ready by the end of the next week

**Comment by pshendry** [comment]
Awesome! Once I've learned the ins and outs of this thing a bit more, I'll do what I can to help.

**Comment by henninghorn** [comment]
That sounds awesome @nolimits4web ! 👍 
- Currently I'm looking through the source code to figure out how each component work :)

**Comment by scriptPilot** [comment]
I am currently working on a complete framework to build web applications - I would appreciate to have some comments on the **Feedback** thread in the issue list - for the scope first:

https://github.com/scriptPilot/framework7-vue-firebase

Dennis
