### ISSUE TITLE
 No notifications are displayed

### ISSUE THREAD

**Issue by Evhanz** [nolimits4web/Framework7-Vue#214]
I have the following error:
- I'm trying to create a notification when I call a button
new Vue({
  el: '#app',
  data: { ..},
  methods:{
    guardarCaja: function(){
       var v = this;
       console.log(this.$options.framework7);
       this.$options.framework7.addNotification({
            message: 'Nice yellow button',
            button: {
                text: 'Click me',
                color: 'yellow'
            },
             onClose: function () {
                myApp.alert('Notification closed');
            }
      });
    }
 },
framework7: {
    root: '#app', ...

Console does not show error, but notification is not displayed

**Comment by miladmeidanshahi** [comment]
anybody know how to solve ?

how to run notification on vue ?

**Comment by nolimits4web** [comment]
What is `this.$options.framework7`? You should use `this.$f7. addNotification...`
