### ISSUE TITLE
how to go back to the default page via f7-link?

### ISSUE THREAD

**Issue by fishenal** [nolimits4web/Framework7-Vue#226]
```
		<f7-toolbar labels>
			<f7-link icon-f7="home" text="home" href="/"></f7-link>
			<f7-link icon-f7="favorites" text="list" href="/list"></f7-link>
			<f7-link icon-f7="document_text_fill" text="chart" href="/chart"></f7-link>
		</f7-toolbar>
```

```
{
    path: '/chart/',
    component: require('./assets/vue/pages/chart.vue')
  },
  {
    path: '/list/',
    component: require('./assets/vue/pages/list.vue')
  },
```

link to other route is ok, but can't go back to the default first page, that page is main.vue, include f7-statusbar and #app(seems like main layout), so shell i set route '/' as main.vue? i dont think that's author purpose.

how should i do?

**Comment by fishenal** [comment]
otherwise, i can make main.vue as a assets/pages,  on this way i can router pages as my wish.
but there has another problem as first enter the page is blank page~ because main.vue really dont load assets/pages/main.vue as default.....

and i tried to set redirect / to /main, seems not work

**Comment by imrealashu** [comment]
@fishenal any luck with this ?

**Comment by nolimits4web** [comment]
Check how it is done in Kitchen sink at https://github.com/nolimits4web/Framework7-Vue/blob/master/kitchen-sink/index.html#L38-L41. There is main route specified for this https://github.com/nolimits4web/Framework7-Vue/blob/master/kitchen-sink/routes.js#L58-L60

**Comment by fishenal** [comment]
well, seems like the key is to set a default 'url' in <f7-view>, i will try this, thanks very much.
