### ISSUE TITLE
Input element do not get style applied when use scoped style.

### ISSUE THREAD

**Issue by lxmfly123** [nolimits4web/Framework7-Vue#227]
### Framework7-Vue version: 
**0.9.2**

### Sample code:
```vue
<template lang="pug">
f7-list
  f7-list-item
    f7-input(type="text")
</template>

<style scoped>
input {
  color: red;
}
</style>
```

### Should be:
Text in input is RED

### Actually is: 
Text in input is still BLACK like default.

**Comment by lxmfly123** [comment]
There is a bug in corresponding render functions.

**Comment by nolimits4web** [comment]
Such weak selector can't override default styles. Use more strict selector
