### ISSUE TITLE
Framework7 V2 changes

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7-Vue#229]
Hi Vladimir,

What I am interested in, is what will change with Framework7 V2 in the background.

Thanks,

Dennis

**Comment by nolimits4web** [comment]
Hi,

Can't say for sure, because haven't started to work on F7Vue 2, but there shouldn't be very much changes, at least in layout, as i can handle v2 markup changes inside of F7 Vue components.

**Comment by scriptPilot** [comment]
@nolimits4web - OK, thank your for that information. Without making pressure, so you have a rough planning for v2 / v2-vue ?

**Comment by scriptPilot** [comment]
OK - Answered here: https://github.com/nolimits4web/Framework7/issues/1768 :-)
