### ISSUE TITLE
About the way of importing compontnents

### ISSUE THREAD

**Issue by WalterZou** [nolimits4web/Framework7-Vue#231]
@nolimits4web 
Hi,
In my case, i used framework7-vue as the main framework of mobile webapp. But, there is a problem, that after build with webpack, the vendor js file and main js file were to big for mobile.

I figured out that all of framework7 components imported by default, can we import components when actually need them, like:
```
import {F7Page, F7Navbar} from 'framework7-vue'
```

**Comment by nolimits4web** [comment]
Same as #219
