### ISSUE TITLE
Representing current state in browser URL

### ISSUE THREAD

**Issue by bcarroll22** [nolimits4web/Framework7-Vue#234]
Hey sorry if this is already covered somewhere, I couldn't find it in any issues or the docs.

Basically, I'm looking for a way to make it so that the browser URL bar matches the current state of the app. Is that possible with f7? I want it to allow for things like the user typing `localhost:8080/about` and going straight to the about? Is that currently covered with f7 somehow?

**Comment by nolimits4web** [comment]
Looks like you are looking for `pushState` parameter http://framework7.io/docs/init-app.html that you need to pass to f7 parameters

**Comment by lizhouyang** [comment]
http://framework7.io/docs/init-app.html   There isn't any `pushState `parameter, can you say more?

**Comment by lizhouyang** [comment]
http://framework7.io/docs/init-app.html   There isn't any `pushState `parameter, can you say more?

**Comment by nolimits4web** [comment]
@lizhouyang everything is correct there. This parameter must be set on `view` in v2

**Comment by lizhouyang** [comment]
@nolimits4web  `
    <f7-view id="main-view" url="/"  main :pushState="true"></f7-view>` that works, thanks
