### ISSUE TITLE
popover covered by modal-overlay

### ISSUE THREAD

**Issue by transtone** [nolimits4web/Framework7-Vue#24]
When put a popover in f7-page element(a components), It will covered by modal-overlay. 
It must be put in `index.html`?

**Comment by nolimits4web** [comment]
@transtone yes, at the moment it should be as a child of app root element (I assume it is in your index)

**Comment by nolimits4web** [comment]
Should be fixed now with latest version of F7

**Comment by haris0** [comment]
can you give me example how to use popover in framwork7 vue, i'm still using v1
