### ISSUE TITLE
Virtual lists in popup can't initialize before search

### ISSUE THREAD

**Issue by centrual** [nolimits4web/Framework7-Vue#35]
Hello,

I trying to make virtual list in popup, but i can't initialize virtual list before search.
Fiddle: https://jsfiddle.net/k2z8jo9x/

Direct media lists are not performing for mobile. I trying to make phone code list with country flag and name (~180 list items). Like that: https://vgy.me/GZIoe7.png

**Comment by nolimits4web** [comment]
It happens because VL doesn't have the size (because popup is hidden and have no size as well). Just call VL's resize methods when popup is opened: https://jsfiddle.net/76tg4hv3/
