### ISSUE TITLE
about this.$emit('tab:show', e);

### ISSUE THREAD

**Issue by gongph** [nolimits4web/Framework7-Vue#39]
hi @nolimits4web , in `tab.vue` component , i see the `@tab:show="onTabShow"` ，but i don't know much about it. When does `@tab:show` event trigger?

**Comment by nolimits4web** [comment]
http://framework7.io/vue/tabs.html#tab-events

```
<f7-tab @tab:show="doSomething">Tab content</f7-tab>

**Comment by gongph** [comment]
Hi, @nolimits4web  . I wrote a demo on jsFiddle, but why not? Can you help me to see it? 
https://jsfiddle.net/cqdqyfe4/
