### ISSUE TITLE
I got error theme IOS

### ISSUE THREAD

**Issue by chansovann** [nolimits4web/Framework7-Vue#448]
Hello how i can fix for Framework7-vue version 3.4.0 that it show me some error like this 
framework7-vue/utils/plugin.js:29
"Uncaught TypeError: Cannot read property 'ios' of undefined"
$theme.ios = !!(Framework7.Device || Framework7.device).ios;

Thank for help :)

**Comment by ChanJianxun** [comment]
I got the same error when I using the version 3.4.0 of Framework7-vue.Who can give me a hand ?

**Comment by wlsgithub** [comment]
I also encountered the same problem. If you have a solution, please tell me about it.Thanks.
