### ISSUE TITLE
Ошибка в item-after в smart-select при использовании в popup

### ISSUE THREAD

**Issue by Marycka9** [nolimits4web/Framework7-Vue#449]
Добрый день.
Использую Ваш фреймворк с vuejs.
У меня в popup есть элемент smart-select, в который передаются данные с vuex.
Список отображается, все отлично. Но, при первом открытии окна, по-умолчанию не выставляется элемент в selected.
Пыталась менять item-after через jQuery - innerHtml и innerText меняется в объекте, но не показывается
Выставляла через проверку selected - не работает (smart-select без popup все прекрасно отображает). Выставляла в ручную элемент по-умолчанию с selected - не работает.
Выставляла через свойство - valueEl - ломается свойство openIn: 'sheet'

Очень надеюсь на Ваш совет, как лучше сделать. Заранее, спасибо!

**Comment by nolimits4web** [comment]
Добрый день! Живой пример или в JS Fiddle было бы хорошо увидеть

**Comment by Marycka9** [comment]
Как можно с Вами связаться? Развернуть то, что нужно показать, займет не один час и то, если площадка потянет.

**Comment by nolimits4web** [comment]
Мне не нужно разворачивать весь проект. Достаточно создать JSFiddle с минимумом достаточным чтобы увидеть проблему
