### ISSUE TITLE
Duplicate Navbars in Swipable Tabs Page

### ISSUE THREAD

**Issue by bencompton** [nolimits4web/Framework7-Vue#48]
On the Swipable Tabs page, it ends up that the children arrays of pageEl contain two references to the Navbar (one in fixedList and one in pageContentEl). In React, it only renders the navbar once, but it shows a warning in the console about the duplicate elements. Vue renders it once and shows no warnings. The current plan is to update the reactifyVue code to get rid of duplicate element and avoid the warning, but I thought I'd mention it here to see if it is worth fixing in case a future version of Vue works differently and produces inconsistent results.

**Comment by nolimits4web** [comment]
They shouldn't be duplicated of course, i'll fix it
