### ISSUE TITLE
Kitchen Sink swiper missing pagination bullets

### ISSUE THREAD

**Issue by jascolley** [nolimits4web/Framework7-Vue#49]
@bencompton and I are in the process of building a react version of the vue components and our own kitchen sink to mimic yours to keep the two in sync. Upon implementing the swiper component I noticed ours is displaying the pagination bullets for bottom two swiper components. The Framework7-Vue kitchen sink does not display these bullets. After reviewing the code in framework7 and stepping through everything it seems to me like these should be showing since you are passing in the pagination flag to the swiper component. You can view our working example in our kitchen sink here:

[kitchen sink](https://bencompton.github.io/framework7-react/reactify-vue/)

**Comment by nolimits4web** [comment]
Thanks, of course it should be there. It is new issue with latest Vue release for the props that have mixed types like [String, Boolean] here, so it started to treat `pagination` parameter as empty string rather than boolen `true`
