### ISSUE TITLE
Tiny suggestions/corrections for kitchen-sink

### ISSUE THREAD

**Issue by cornelisse** [nolimits4web/Framework7-Vue#5]
I noticed in a typo in index.html
```
  <link rel="stylesheet" href="framework7/framework7.min.ios.css">
  <link rel="stylesheet" href="framework7/framework7.min.ios.colors.css">
```
this should be:
```
<link rel="stylesheet" href="framework7/framework7.ios.min.css">
<link rel="stylesheet" href="framework7/framework7.ios.colors.min.css">
```
The ```min``` is at the wrong position :-)

**Comment by cornelisse** [comment]
If I add the framework7.js.map then I get no errors in my console.
But perhaps, adding framework7.min.js and framework7.min.js.map to the framework7 directory of kitchen-sink might be preferable.

Ps,
This suggestion was only possible after you launched the 1.15 version of F7 today :-)
Many thanks !!!

**Comment by cornelisse** [comment]
I haven't figured it out how to deal with the ```<f7-icon>``` tag but if you change the floating action button in FAB.vue and FAB-Dail.vue in
```
    <f7-fab color="pink">
      <i class="f7-icons">add</i>
    </f7-fab>
```
and
```
      <f7-fab>
        <i class="f7-icons">add</i>
        <i class="f7-icons">close</i>
      </f7-fab>
```
the floating action button has also the proper sign.

Ps
(I included the Framework7-icons to the kitchen-sink)

**Comment by nolimits4web** [comment]
F7-icon tag designed to be used with different icon fonts: Font Awesome, F7 Icons, Material Icons and Ionicons. So for F7 Icons font it should be `<f7-icon f7="add"></f7-icon>`

**Comment by cornelisse** [comment]
Great !!!
it works.
Just changed the code to 
```
      <f7-fab>
        <f7-icon f7="add"/>
        <f7-icon f7="close"/>
      </f7-fab>
```
and that works like a charm !
Amazing feature :-)
