### ISSUE TITLE
Vue key for list elements

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7-Vue#58]
Referring to [Vue key parameter documentation](https://vuejs.org/v2/guide/list.html#key), it should be incorporated within v-for loops, mainly used in list elements. Is there any way to add `key` element in v-for loops? data-key will be accepted, but key not so far.

**Comment by nolimits4web** [comment]
Sorry, didn't get your question. Can you explain more detailed what you are trying to achieve?

**Comment by scriptPilot** [comment]
Ok, so there should be a key attribute for list elements, to assign a specific key as described in the Vue.js docs above:

> <div v-for="item in items" :key="item.id">
>   
> </div>

```
<f7-list>
  <f7-list-item v-for="item in items" :title="item.title" :key="item.key"></f7-list-item>
</f7-list>
```

Or is there any better way? Because the same could be usefull for card or every other content which is created by v-for.

**Comment by nolimits4web** [comment]
It doesn't require any implementation from my side. It is already there, you just have to use appropriate data to make it work. It is handled by Vue internally, not by components

**Comment by scriptPilot** [comment]
@nolimits4web - Unfortunately I don't get it work ...

Working example: https://jsfiddle.net/s2b5mbLq/ - You can try here and see, each <li> element has a key attribute.

There is no key attribute with:

```
<f7-list>
  <f7-list-item v-for="(title, key) in titles" :title="title" :key="key"></f7-list-item>
</f7-list>
```
and

```
data: function () {
  return {
    titles: {
      name: 'Title A',
      surname: 'Title B'
    }
  }
}
```

**Comment by nolimits4web** [comment]
You've probably got wrong about what it means and its usage:
```
<f7-list>
  <f7-list-item v-for="(title, key) in titles" :title="key" :after="title"></f7-list-item>
</f7-list>

<f7-list>
  <f7-list-item class="mymessage" v-for="message in messages" :title="message.text" :key="message.id"></f7-list-item>
</f7-list>
```
```js
data: function () {
  return {
    titles: {
      name: 'Title A',
      surname: 'Title B'
    },
    messages: [
      {
        id: 1,
        text: 'Message 1'
      },
      {
        id: 2,
        text: 'Message 2'
      }
    ]
  };
}
```

`key` attribute is used not to display object property key. Here is how v-for for objects https://vuejs.org/v2/guide/list.html#Object-v-for

Here is what `key` attributes is used for:
> To give Vue a hint so that it can track each node’s identity, and thus reuse and reorder existing elements, you need to provide a unique key attribute for each item

https://vuejs.org/v2/guide/list.html#key
