### ISSUE TITLE
only mainView object is accessible in this.$f7

### ISSUE THREAD

**Issue by GuillaumeBiton** [nolimits4web/Framework7-Vue#69]
$f7 can easily access 'mainView' throw $f7.mainView

but I can't find the way to get 'anotherView' like we did by addView methods.

**Comment by bencompton** [comment]
If you enumerate `$f7.views`, that should let you find the view you want.

**Comment by GuillaumeBiton** [comment]
I agree but it could be interesting to have quick access like it can be done without vue.

maybe something like:

    f7-view(name='main')
    f7-view(name='left')

**Comment by bencompton** [comment]
Yeah, it would even be nice in Framework7 to have a method like that to access any view by name, e.g.: `myApp.getView('left')`. Then in Vue, a view could be accessed like this: `$f7.getView('left')`.

**Comment by nolimits4web** [comment]
Just merged @GuillaumeBiton PR with few additions, so now each view can be accessed by name as `$f7.leftView` or `$f7.views.left`
