### ISSUE TITLE
Statusbar issue

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7-Vue#71]
Requested is `#app` element instead of lunching the application in `body`.
But now I have some trouble with the status bar in full screen mode (homescreen app / iPhone SE).

**According Framework7-Vue docs I do:**
index.html
````
<body>
    <div id="app"></div>
</body>
````
app.vue
````
<template>
  <div id="app">
    <f7-statusbar></f7-statusbar>
````
Result: Statusbar overlay is displayed 20px to low

**Changing to:**
index.html
````
<body>
    <div class="statusbar-overlay"></div>
    <div id="app"></div>
</body>
````
app.vue
````
<template>
  <div id="app">
    <!--<f7-statusbar></f7-statusbar>-->
````
Result: Statusbar / Navbar are displayed well, but popups, side panels etc open with 20px padding to the top

**Comment by scriptPilot** [comment]
For me, it is fixed with the following css additions - but is it the right way?
````
  body {
    padding-top: 0px !important;
  }
  .statusbar-overlay {
    background: #000000;
  }
  .with-statusbar-overlay .view-main {
    margin-top: 20px !important;
  }
````

**Comment by scriptPilot** [comment]
Ah ... much better solution I think:

````
.with-statusbar-overlay body {
  padding-top: 0px !important;    
}
.with-statusbar-overlay #app {
  padding-top: 20px;
}`
````

**Comment by nolimits4web** [comment]
It was fixed in F7 core itself, so will be fixed here with using next release of F7

**Comment by scriptPilot** [comment]
Fine!

**Comment by devgeeks** [comment]
Any news on when that next release might be? F7core seems to have not had a new release since December 17.

**Comment by nolimits4web** [comment]
@devgeeks going to be released this weekend
