### ISSUE TITLE
Changing data does not update textarea dom?

### ISSUE THREAD

**Issue by valnub** [nolimits4web/Framework7-Vue#74]
I created this Twitter demo app: https://github.com/valnub/twitvue03

In `home.vue` I wanted to fix a minor issue where this component would not be emptied after posting a new tweet:

`f7-input(type='textarea', placeholder='New tweet', v-model='newTweet')`

See https://github.com/valnub/twitvue03/blob/master/src/home.vue

So, I changed this line (92):

```
else {
  window.f7.closeModal('.picker-new-tweet');
}
```

To this:

```
else {
  self.newTweet = "";
  window.f7.closeModal('.picker-new-tweet');
}
```

But this doesn't work. The textarea still shows the old value which was typed into it by the user.

What's wrong? Is there a bug in this component or did I do something wrong?

**Comment by nolimits4web** [comment]
Should be fixed with https://github.com/nolimits4web/Framework7-Vue/commit/ea9bd407bf6b2e8d08d71c943736a0939e7ea861

**Comment by valnub** [comment]
@nolimits4web Great! Thanks, Vladi. Is the fix already available via NPM as well as Cloudflare CDN?

**Comment by nolimits4web** [comment]
Not yet

**Comment by nolimits4web** [comment]
Released
