### ISSUE TITLE
how can i add click listener on virtual list

### ISSUE THREAD

**Issue by kael777** [nolimits4web/Framework7-Vue#8]
i add this code
```
<f7-list 
        id="search-list"
        class="searchbar-found"
        media-list
        virtual 
        inset 
        :virtual-items="mysub"
        :virtual-height="63"
        :virtual-search-all="searchAll"
        >
        <t7-template>
          <f7-list-item @click="onItemClick" media-item link="#" :title="'{{Username}}'" :subtitle="'left:{{Chips}}'">
          </f7-list-item>
        </t7-template>
      </f7-list>
```
try to handle each item's click,but it seems not work,it is version 0.5.7 i used

**Comment by kael777** [comment]
and here seems a spell wrong
https://github.com/nolimits4web/Framework7-Vue/blob/master/src/components/list-item.vue#L27
did that mean 'disabled': self.disabled?

**Comment by nolimits4web** [comment]
Click handler for VL should be added manually, e.g. in `mounted` callback:
```
$(this.el).on('click', '.virtual-list li', function (){
  //handle click
});

**Comment by ytbryan** [comment]
Thank you for framework7. I was trying to add a listener to each swipeout element in a virtual list. 

And this does not seems to work at all. Is there a workaround or is there issue with my code? 

I also tried using $$('.swipeout').on directly but to no avail. Thank you!  

The following is my code. 
>        $$('.virtual-list li.swipeout').on('swipeout:delete', function (e) {
>             axios.delete("/tasks/" + $(this).attr('data-task-id') + ".json")
>                 .then(function (response) {
>                     alert(response)
>                 })
>                 .catch(function (error) {
>                     alert(error)
>                 })
>         })
> 

cc @nolimits4web

**Comment by ytbryan** [comment]
@nolimits4web How will you suggest to add the click listener for normal framework7 (non-vue) where there is no mount callback? 

And since each item is rendered as you scroll, some items have no listeners added.

**Comment by nolimits4web** [comment]
@ytbryan it is possible to do it with Vue rendering and listen events in Vue way (as in https://github.com/nolimits4web/Framework7-Vue/blob/master/kitchen-sink/pages/virtual-list-vue.vue). In normal F7, it can be achieved using live event:
```js
$('.virtual-list').on('click', 'a', function () {
  //do something
});

**Comment by ytbryan** [comment]
@nolimits4web thank you for the answer. And thank you for framework7
