### ISSUE TITLE
Error on f7-page components

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7-Vue#81]
Error in JS console after latest changes to master:

> [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "name" 
> (found in component <f7-page>)

**Comment by nolimits4web** [comment]
But as error message states it looks like you are trying to change page prop directly from child component. You should avoid it

**Comment by nolimits4web** [comment]
@scriptPilot can we close it or is it really an issue?

**Comment by scriptPilot** [comment]
@nolimits4web - Seems fine now, I'll close the incident.
