### ISSUE TITLE
Panel navbar vanishes on ios after first use

### ISSUE THREAD

**Issue by dsl101** [nolimits4web/Framework7-Vue#85]
Thanks @nolimits4web for the pointer to the correct layout in that other ticket. Since it's closed and in the wrong place, I decided to make a new one here.

I can now close the panel, but the panel navbar isn't shown when sliding on an iphone after the first open/close cycle. It works fine in the browser, and it 'appears' when the panel stops moving. But in between it's blank. The panel _content_ is shown fine, so it's just a visual glitch. This is the panel setup I have, in place of the one in that template:

    <f7-panel left cover layout="dark">
      <f7-view id="left-panel-view">
        <f7-navbar title="Units">
          <f7-nav-right>
            <f7-link close-panel>X</f7-link>
          </f7-nav-right>
        </f7-navbar>
        <f7-pages>
          <f7-page>
            <f7-list form>
              <template v-for="typeName in allTypes">
              <f7-list-button
                close-panel
                @click="type = typeName"
              >{{typeName}}</f7-list-button>
              </template>
            </f7-list>
          </f7-page>
        </f7-pages>
      </f7-view>
    </f7-panel>

and here's a codepen which shows the glitch: http://codepen.io/anon/pen/XpEwjP/

**Comment by nolimits4web** [comment]
Yes, sometimes it happens (the fix already added to core F7). Just add the following CSS rule as temporary fix:
```css
.navbar {
  transform: translate3d(0,0,0);
}

**Comment by dsl101** [comment]
Tx. Can I take it from your comment that `npm update` will eventually fix it permanently when the fix in F7 is available? Or do I need to do something else?

**Comment by nolimits4web** [comment]
It is already released
