### ISSUE TITLE
f7-statusbar

### ISSUE THREAD

**Issue by silasmatheus** [nolimits4web/Framework7-Vue#95]
In IOS f7-statusbar not working when i put it into body > div#app > f7-statusbar.  Is it possible add the f7-statusbar directly in body ?

![image](https://cloud.githubusercontent.com/assets/1700605/22797116/52b56270-eee4-11e6-8983-1fc31d400b89.png)

**Comment by nolimits4web** [comment]
Update to latest F7 and F7 Vue plugins, it is fixed there
