### ISSUE TITLE
:checked and @change not working on switch input

### ISSUE THREAD

**Issue by centrual** [nolimits4web/Framework7-Vue#97]
Hello framework7 community!

I updated framework7-vue version to latest in my project and switch input's change method not working anymore. I changed to `@input` and it worked. But big problem is :checked property isn't working anymore too, ~i can't set default value~.

**Update:** i changed `:checked` to `:value` and it's working now.

https://jsfiddle.net/centrual/a353jcds/4/

Have a great day!

**Comment by dlindenkreuz** [comment]
This should be somewhere in the docs. Both [F7-Vue](http://framework7.io/vue/form-elements.html) and [F7-React](http://framework7.io/react/form-elements.html) both document a `checked` property which does not apply to all input elements.
